### ISSUE TITLE
Nasa API changed

### ISSUE THREAD

**Issue by jenyquist** [brendanv/nasa-api#1]
Does this still work?  I installed the package and ran the apod example but received a 404 error for the request.

**Comment by jenyquist** [comment]
I believe the problem is the url path has changed.

For example: 
https://api.nasa.gov/planetary/apod
has replaced
https://api.data.gov/nasa/planetary/apod

**Comment by samgeen** [comment]
Seconded - searching for ".gov" in the files and replacing the old URL with the new one seems to fix the issues I was having.

**Comment by brendanv** [comment]
Fixed in #3. Thanks for the report, sorry I missed the issue! Thanks to @asmith26 for the fix.
