### ISSUE TITLE
Error in the readme

### ISSUE THREAD

**Issue by jenyquist** [brendanv/nasa-api#2]
> > > from nasa import apod
> > > image = earth.image(lat=1.5, lon=100.75, date='2014-02-01')
> > > image.id
> > > 'LC8_L1T_TOA/LC81270592014035LGN00'

first line should be 
from nasa import earth

**Comment by brendanv** [comment]
Thanks, fixed in 7f06060. Sorry I missed this issue and took so long to fix it...
