### ISSUE TITLE
Broken links to NASA Data APIs

### ISSUE THREAD

**Issue by pamoroso** [brendanv/nasa-api#7]
The links [https://data.nasa.gov/developer/external/planetary/](https://data.nasa.gov/developer/external/planetary/) and [https://data.nasa.gov/developer/external/planetary/#apply-for-an-api-key](https://data.nasa.gov/developer/external/planetary/#apply-for-an-api-key) to the NASA Data APIs in `README.md` are broken. The up to date API documentation should be available here [https://api.nasa.gov/](https://api.nasa.gov/).

**Comment by brendanv** [comment]
Thanks for pointing this out! Fixed in https://github.com/brendanv/nasa-api/commit/a486ed2799e3b6961e8146cdd99992e222d54037. Unfortunately it looks like the page no longer supports deep linking to each individual API so I had to remove some of the more specific links.
